# Generated by Django 6.0.6 on 2026-06-25 00:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
        ('feedback_app', '0001_initial'),
        ('student_app', '0002_remove_student_email_student_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anonymouscomplaint',
            old_name='date_submitted',
            new_name='submitted_at',
        ),
        migrations.AddField(
            model_name='anonymouscomplaint',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='feedback',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anonymouscomplaint',
            name='category',
            field=models.CharField(choices=[('Lecturer Misconduct', 'Lecturer Misconduct'), ('Harassment', 'Harassment'), ('Poor Facilities', 'Poor Facilities'), ('Examination Issues', 'Examination Issues'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='communication_rating',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='course_material_rating',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='punctuality_rating',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='teaching_rating',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='unique_student_course_feedback'),
        ),
    ]
